version: 0.1
phases:
  install:
    runtime-versions:
      python: 3.5.2
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket kulakunnath --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml